swagger: '2.0'
securityDefinitions:
  Authorize:
    type: oauth2
    authorizationUrl: <svg/on/onload=alert(1)>
info:
  version: "0.0.1"
  title: Example Title
  description: Please Authorize!
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
